Devworks/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Customer_ID__c</fullName>
        <externalId>true</externalId>
        <label>Customer ID</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Devworks/src/objects/MDM__c.object
<CustomObject>
    <label>MDM</label>
    <nameField>
        <displayFormat>MDM-{0000}</displayFormat>
        <label>MasterRecordNumber</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MDMs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Devworks/src/classes/AccountCustomerDetail.cls
public with sharing class AccountCustomerDetail {
	@AuraEnabled
    public static String getOriginId(Id AccountId)
    {
        String retval = '';
        List<Account> accntlist = new List<Account>([select Customer_ID__c from Account where ID = :AccountId]);
        System.debug('Size '+accntlist.size());
        if(accntlist.size() > 0 )
        {
            retval = accntlist[0].customer_id__c;
        }
        System.debug('retval '+retval);
        return retval;
    }
    @AuraEnabled
    public static mdm__c GetMDMKey(String RecordId)
    {
        mdm__c Resp = MDMKeyGen.GetMDMKey(RecordId);
        return Resp;
    }
}