Devworks/src/objects/Camping_Item__c.object
<CustomObject>
    <fields>
        <fullName>Packed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Packed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Camping Item</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Camping Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Devworks/src/classes/CampingListController.cls
public class CampingListController {
	@AuraEnabled
    public static List<Camping_Item__c> getItems()
    {
        List<Camping_Item__c> cmpitmlst = [SELECT NAME,PRICE__C, QUANTITY__C,PACKED__C FROM CAMPING_ITEM__C LIMIT 10];
        return cmpitmlst;
    }
    
    @AuraEnabled
    public static Camping_Item__c saveItem(Camping_Item__c campingitem)
    {
        upsert campingitem;
        return campingitem;
    }
}