Devworks/src/objects/MDM__c.object
<CustomObject>
    <fields>
        <fullName>External_Id__c</fullName>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>30</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>MasterRecordId__c</fullName>
        <defaultValue>&quot;Temp&quot;</defaultValue>
        <label>MasterRecordId</label>
        <length>30</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Record_Status__c</fullName>
        <label>Record Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Duplicate</fullName>
                </value>
                <value>
                    <fullName>Original</fullName>
                </value>
                <value>
                    <fullName>Void</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>MDM</label>
    <nameField>
        <displayFormat>MDM-{0000}</displayFormat>
        <label>MasterRecordNumber</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MDMs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Devworks/src/classes/MDMKeyGeneration.cls
@RestResource(urlMapping='/MDMKeyGeneration/*')
global with sharing class MDMKeyGeneration {
@HttpGet
    global static MDM__c getMDMKey() {
        RestRequest request = RestContext.request;
        // grab the AccountId from the end of the URL
        String AccountId = request.requestURI.substring(request.requestURI.lastIndexOf('/')+1);
        System.debug('AccountId '+AccountId);
        MDM__c result = [SELECT MasterRecordId__c, Record_Status__c FROM MDM__c WHERE External_Id__c = :AccountId];
        return result;
    }
}